# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81777f0bd308d107136f20e99edfab6991c3c1cdc3ae41526d6a3c228a739b9083306b64e8dda41c98b83964c49d552bdc530f3202ce94a52a1b3ec44de8871e

test:
  secret_key_base: 66f4132f49b39046c0cf27585207814172b8ea1d3538ce2364ed6369c99b0d5ed2f22ced58396d318e1f34f7e09401ca95cea32f63240157265447a500002683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
